### ISSUE TITLE
Documentation for data-source and post-processors is missing

### ISSUE THREAD

**Issue by khawarizmus** [digitalocean/packer-plugin-digitalocean#147] opened 2024-06-25 05:17 UTC
#### Overview of the Issue

The documentation for the [digitalocean-image](https://developer.hashicorp.com/packer/integrations/digitalocean/digitalocean/latest/components/datasource/image) data-source is broken.

Same behaviour for [digitalocean-import](https://developer.hashicorp.com/packer/integrations/digitalocean/digitalocean/latest/components/post-processor/import) post-processor

#### Reproduction Steps

Go to the [documentation](https://developer.hashicorp.com/packer/integrations/digitalocean/digitalocean) and check

**Comment by andrewsomething** [comment] 2024-06-28 21:59
Thanks for flagging this. The changes in https://github.com/digitalocean/packer-plugin-digitalocean/pull/148 seemed to resolve this for the digitalocean-import post-processor:

https://developer.hashicorp.com/packer/integrations/digitalocean/digitalocean/latest/components/post-processor/digitalocean-import

Unfortunately it did not fix the data source. We'll continue to investigate.

**Comment by andrewsomething** [comment] 2024-07-19 16:59
@lbajolet-hashicorp  Any chance you can help identify the issue here as you handled the initial migration? It's not clear to me why the post-processor docs are not getting picked up.

**Comment by lbajolet-hashicorp** [comment] 2024-07-22 13:05
Hi @andrewsomething,

Thanks for the ping. Looks like there's a typo in the name for the datasource, which is likely why the link won't work.

I've opened a PR to help fix this, hopefully that's all that's needed here!

**Comment by andrewsomething** [comment] 2024-07-22 14:04
Thanks @lbajolet-hashicorp! Stared at the contents of that file for so long without catching the typo in the name itself. :man_facepalming:

**Comment by lbajolet-hashicorp** [comment] 2024-07-22 14:06
All good, been here done that :)

I'd suggest running the manual publish action on main now that the PR's been merged, this should hopefully fix that on the web docs

**Comment by andrewsomething** [comment] 2024-07-22 15:44
Confirmed that it now displays as expected:

https://developer.hashicorp.com/packer/integrations/digitalocean/digitalocean/latest/components/data-source/digitalocean-image

Thanks again @lbajolet-hashicorp!

**Closed by andrewsomething** 2024-07-22 15:44 UTC
Labels: bug
